sudo: required

language: go

dist: xenial

services:
- docker

addons:
  apt:
    packages:
    - docker-ce
    - apt-cacher-ng

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
    - $TRAVIS_BUILD_DIR/.gitian-builder-cache
    - /var/cache/apt-cacher-ng

os:
- linux

go:
# reason for bumping 1.11.x to 1.11.4+ is this: https://github.com/golang/go/issues/30446#issuecomment-468038052
- "1.11.4"
- "1.12"


env:
  global:
    - TM_VERSION=v0.31.5
    - BUILD_VERSION=$(echo ${TRAVIS_COMMIT} | cut -c 1-10)
    - MAIN_GO_VERSION=1.12
    - GORACE="halt_on_error=1"
    - FORCE_TM_TEST=1
    - VERSION=$(git describe --tags --abbrev=9 | sed 's/^v//')
    - COMMIT=$(git log -1 --format='%H')
    - IMAGE_NAME="iov1/bnsd:${BUILD_VERSION}"

install:
- go get -d github.com/tendermint/tendermint/... ;
  cd ${GOPATH}/src/github.com/tendermint/tendermint ;
  git checkout ${TM_VERSION} ;
  make get_tools && make check && make install ;
  cd -;

script:
- set -eo pipefail
- make protolint;
- make protodocs;
- make install;
- make all;
- if [[ "$TRAVIS_GO_VERSION" == "$MAIN_GO_VERSION" ]]; then
     make cover;
     ./coverage/upload.sh;
   fi;
- printenv TRAVIS_COMMIT_MESSAGE > commit.msg
- unset TRAVIS_COMMIT_MESSAGE && printenv | grep -Ev "PATH|path|GEM" > env.list
- export TRAVIS_COMMIT_MESSAGE=`cat commit.msg` && rm -rf commit.msg
- docker run -it --rm --env-file env.list -v "$(pwd):/usr/src/app" iov1ops/danger:latest > danger.out; cat danger.out
- if [[ "$TRAVIS_GO_VERSION" == "$MAIN_GO_VERSION" && "$TRAVIS_OS_NAME" == "linux" ]]; then
    release_latest=$( [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_TAG" == "" && "$TRAVIS_PULL_REQUEST_BRANCH" == "" ]] && echo "yes" || echo "no" );
    release_tag=$( [[ "$TRAVIS_TAG" != "" ]] && echo "yes" || echo "no" );

    if [[ $release_latest == "yes" || $release_tag == "yes" ]]; then
      ./contrib/gitian-build.sh linux ;
     tar -zxf $TRAVIS_BUILD_DIR/bns-build-linux/build/out/bnsd-${VERSION}-linux-amd64.tar.gz -C ${TRAVIS_BUILD_DIR} ;
     docker build --pull  --file ${TRAVIS_BUILD_DIR}/cmd/bnsd/Dockerfile --tag ${IMAGE_NAME} . ;
    fi;

    if [[ $release_latest == "yes" ]]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker tag  "iov1/bnsd:${BUILD_VERSION}" "iov1/bnsd:latest" ;
      docker push "iov1/bnsd:latest";
      docker logout;
    fi;

    if [[ $release_tag == "yes" ]]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker tag  "iov1/bnsd:${BUILD_VERSION}" "iov1/bnsd:$TRAVIS_TAG" ;
      docker push "iov1/bnsd:$TRAVIS_TAG";
      docker logout;
    fi;
  fi;

notifications:
  email: false

# whitelist long living branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
  - master
  - launch
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/

deploy:
  provider: releases
  api_key:
    ${GITHUB_API_KEY}
  file:
    - ${TRAVIS_BUILD_DIR}/bns-build-linux/build/out/bnsd-${VERSION}-linux-amd64.tar.gz
    - ${TRAVIS_BUILD_DIR}/bns-build-linux/build/out/src/bnsd-${VERSION}.tar.gz
    - ${TRAVIS_BUILD_DIR}/bns-build-linux/result/bns-linux-res.yml
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$

